[project]
name = "microservicio-gestion-especialidades"
version = "0.1.0"
description = "Mock de especialidades para SYSACAD"
authors = [{ name = "Equipo SYSACAD" }]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "flask==3.0.2",
    "flask-sqlalchemy==3.1.1",
    "flask-migrate==4.0.7",
    "python-dotenv==1.0.1",
    "requests==2.32.3",
    "gunicorn==21.2.0",
    "pytest==9.0.2",
]

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[tool.uv]
# Sin extras ni dev-dependencies en este microservicio mock.
